micronaut:
  server:
    cors:
      enabled: true
  security:
    authentication: bearer
    enabled: true
    apiKeys:
      #kid: key
  http:
    services: # private network only
      repository:
        url: ${REPOSITORY:`http://repository:8080`}
archinsight:
  repositoryAuthToken: ${REPOSITORY_TOKEN}
