pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenCentral()
    }
}

rootProject.name = 'insight'

gradle.ext.archinsightVersions = [
    contracts: '3.0.3',
    editorSupport: '3.0.3',
    graphviz : '3.0.3',
    language: '3.0.3',
    workbench: '3.0.3',
    web     : '3.0.3',
    renderer: '3.0.3',
    cli     : '3.0.3',
    vscode  : '3.0.10'
]

include 'archinsight-web'
include 'archinsight-renderer'
include 'archinsight-cli'
include 'archinsight-vscode'
