pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenCentral()
    }
}

rootProject.name = 'insight'

gradle.ext.archinsightVersions = [
    language: '3.0.0',
    web     : '3.0.0',
    renderer: '3.0.0',
    cli     : '3.0.0-snapshot.2',
    vscode  : '3.0.2'
]

include 'archinsight-web'
include 'archinsight-renderer'
include 'archinsight-cli'
include 'archinsight-vscode'
