FROM alpine:latest as builder
WORKDIR /app

RUN apk add --update --no-cache nodejs npm
COPY . /app

ENV NPM_CONFIG_LOGLEVEL verbose
RUN npm ci && npm run build

FROM alpine:latest
WORKDIR /app

COPY --from=builder /app/dist .
COPY --from=builder /app/package*.json ./

ENV NPM_CONFIG_LOGLEVEL verbose
RUN apk add --update --no-cache --no-cache nodejs npm
RUN npm ci --only=production

CMD ["node", "/app/main"]
