micronaut:
  server:
    cors:
      enabled: true
  security:
    authentication: idtoken
    oauth2:
      clients:
        google:
          client-id: '${OAUTH_CLIENT_ID}'
          client-secret: '${OAUTH_CLIENT_SECRET}'
          scopes:
            - openid
            - profile
            - email
          openid:
            issuer: 'https://accounts.google.com'
    endpoints:
      logout:
        enabled: true
        get-allowed: true
    redirect:
      prior-to-login: false
      login-success: '${PUBLIC_HOST}/auth/ok'
      login-failure: '${PUBLIC_HOST}/auth/fail'
datasources:
  default:
    db-type: POSTGRES
    driverClassName: org.postgresql.Driver
    url: 'jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE}'
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    auto-commit: false
    maximum-pool-size: 10
    minimum-idle: 2
    idle-timeout: 600000
flyway:
  enabled: true
  datasources:
    default:
      enabled: false
      locations:
        - classpath:migration
archinsight:
  devMode: ${DEV_MODE:`false`}
  domain: '${DOMAIN}'
  kid: '${KID}'
  apiToken: '${SECURITY_TOKEN}'
  redirect-uri: '${PUBLIC_HOST}/oauth/callback/google'
