FROM alpine:latest as builder
WORKDIR /app

RUN apk add --update --no-cache nodejs npm openjdk11
COPY . /app

ENV NPM_CONFIG_LOGLEVEL verbose

RUN npm ci && npm run build:prod

FROM alpine:latest
WORKDIR /app

COPY --from=builder /app/dist .
COPY --from=builder /app/run/nginx.conf /etc/nginx/http.d/default.conf
COPY --from=builder /app/run/init.sh /init.sh

RUN apk add --update --no-cache nginx  \
    && adduser -D -g 'www' www \
    && chown -R www:www /var/lib/nginx \
    && chown -R www:www /app   \
    && ln -svf /dev/stdout /var/log/nginx/access.log \
    && ln -svf /dev/stderr /var/log/nginx/error.log

ENV COMPILER_ADDRESS 'http://localhost:3333'
ENV RENDERER_ADDRESS 'http://localhost:3334'
EXPOSE 8080
CMD ["/bin/sh", "/init.sh"]
