import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, dirname, resolve } from "node:path";

const sourceDirectory = resolve("../../src/main/resources/com/github/lonelylockley/insight");
const target = resolve("src/generated/core-source.ts");
const sources = readdirSync(sourceDirectory)
  .filter((item) => item.endsWith(".ai"))
  .sort((left, right) => left.localeCompare(right))
  .map((item) => ({
    sourceName: basename(item),
    source: readFileSync(resolve(sourceDirectory, item), "utf8"),
  }));

mkdirSync(dirname(target), { recursive: true });
writeFileSync(
  target,
  [
    "// Generated by scripts/sync-core.mjs. Do not edit by hand.",
    `export const coreSources = ${JSON.stringify(sources, null, 2)};\n`,
    "export const coreSource = coreSources.map((source) => source.source).join(\"\\n\\n\");\n",
  ].join("\n"),
);

const builtinViewDirectory = resolve(sourceDirectory, "builtin-views");
const builtinViewCatalog = JSON.parse(readFileSync(resolve(builtinViewDirectory, "catalog.json"), "utf8"));
const builtinViews = builtinViewCatalog
  .map((definition) => ({
    ...definition,
    query: readFileSync(resolve(builtinViewDirectory, `${definition.id}.aiq`), "utf8").trimEnd(),
  }))
  .sort((left, right) => left.order - right.order);
const builtinViewsTarget = resolve("src/generated/builtin-view-catalog.ts");
const builtinViewsModule = [
  "// Generated by packages/insight-language/scripts/sync-core.mjs. Do not edit by hand.",
  `export const GENERATED_BUILTIN_VIEW_DEFINITIONS = ${JSON.stringify(builtinViews, null, 2)} as const;\n`,
].join("\n");
mkdirSync(dirname(builtinViewsTarget), { recursive: true });
writeFileSync(builtinViewsTarget, builtinViewsModule);
