import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, dirname, resolve } from "node:path";

const sourceDirectory = resolve("../../src/main/resources/com/github/lonelylockley/insight");
const target = resolve("src/generated/core-source.ts");
const sources = readdirSync(sourceDirectory)
  .filter((item) => item.endsWith(".ai"))
  .sort((left, right) => left.localeCompare(right))
  .map((item) => ({
    sourceName: basename(item),
    source: readFileSync(resolve(sourceDirectory, item), "utf8"),
  }));

mkdirSync(dirname(target), { recursive: true });
writeFileSync(
  target,
  [
    "// Generated by scripts/sync-core.mjs. Do not edit by hand.",
    `export const coreSources = ${JSON.stringify(sources, null, 2)};\n`,
    "export const coreSource = coreSources.map((source) => source.source).join(\"\\n\\n\");\n",
  ].join("\n"),
);
