import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, dirname, resolve } from "node:path";

const sourceDirectory = resolve("../../src/main/resources/com/github/lonelylockley/insight");
const target = resolve("src/generated/core-source.ts");
const sources = readdirSync(sourceDirectory)
  .filter((item) => item.endsWith(".ai"))
  .sort((left, right) => left.localeCompare(right))
  .map((item) => ({
    sourceName: basename(item),
    source: readFileSync(resolve(sourceDirectory, item), "utf8"),
  }));

mkdirSync(dirname(target), { recursive: true });
writeFileSync(
  target,
  [
    "// Generated by scripts/sync-core.mjs. Do not edit by hand.",
    `export const coreSources = ${JSON.stringify(sources, null, 2)};\n`,
    "export const coreSource = coreSources.map((source) => source.source).join(\"\\n\\n\");\n",
  ].join("\n"),
);

const builtinViewDirectory = resolve(sourceDirectory, "builtin-views");
const builtinViewOrder = ["no-filter", "c1", "c2", "c3", "deployment"];
const builtinViews = Object.fromEntries(builtinViewOrder.map((name) => [
  name,
  readFileSync(resolve(builtinViewDirectory, `${name}.aiq`), "utf8").trimEnd(),
]));
const builtinViewsModule = [
  "// Generated by packages/insight-language/scripts/sync-core.mjs. Do not edit by hand.",
  `export type BuiltinDiagramView = ${builtinViewOrder.map((name) => JSON.stringify(name)).join(" | ")};`,
  `export const BUILTIN_VIEW_QUERIES: Record<BuiltinDiagramView, string> = ${JSON.stringify(builtinViews, null, 2)};\n`,
].join("\n");
for (const generatedTarget of [
  resolve("../../archinsight-cli/src/generated/builtin-view-queries.ts"),
  resolve("../../archinsight-vscode/src/generated/builtin-view-queries.ts"),
  resolve("../../archinsight-web/src/lib/generated/builtin-view-queries.ts"),
]) {
  mkdirSync(dirname(generatedTarget), { recursive: true });
  writeFileSync(generatedTarget, builtinViewsModule);
}
