micronaut:
  http:
    services: # private network only
      identity:
        url: ${IDENTITY:`http://identity:8080`}
      compiler:
        url: ${TRANSLATOR:`http://translator:8080`}
      renderer:
        url: ${RENDERER:`http://renderer:8080`}
      repository:
        url: ${REPOSITORY:`http://repository:8080`}
archinsight:
  devMode: ${DEV_MODE:`false`}
  domain: ${DOMAIN}
  # this should be a public url
  loginUrl: ${LOGIN}
  identityAuthToken: ${IDENTITY_TOKEN:``}
  translatorAuthToken: ${TRANSLATOR_TOKEN:``}
  rendererAuthToken: ${RENDERER_TOKEN:``}
  repositoryAuthToken: ${REPOSITORY_TOKEN:``}
  contextPath: '/'
  siteEnabled: true
  ghostSsrEnabled: false
  ghostSsrSecretKey: ''
  trackingEnabled: false
  hotjarSiteId: ''
